### PR TITLE
Build for freedesktop-sdk 21.08beta

### LINKED ISSUE #4: publish 21.08beta version to flathub-beta
freedeskop-sdk 21.08beta has been released, and it has dropped llvm. This means that now this extension is essential to those relying on llvm.

Asking on matrix, the way to do this is to create a branch named `beta` and change the branch name in the manifest, like https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/commits/beta

### PR DESCRIPTION
**Pull request by abderrahim**
~~This needs to be merged to a branch named beta. Until such a branch is created, I'm keeping it a draft~~

Fixes #4

### CODE REVIEW

**Comment by abderrahim** [comment]
What's `-Qunused-arguments`? and why is it enabled only on aarch64?

**Comment by Lctrs** [comment]
`beta` branch has been created.

**Comment by abderrahim** [comment]
Thanks, this is now ready. I'm not sure about the `-Qunused-arguments` on aarch64, but it works fine on x86_64.

**Comment by abderrahim** [comment]
Seems you pushed (something equivalent to) one of the commits when creating the branch. I rebased on top of that.

**Comment by Erick555** [comment]
> What's -Qunused-arguments? and why is it enabled only on aarch64?

Se https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/commit/1ea7d9ad447c88a6710fb12b6c361ce9bd59759c for explanation. It's needed only when build with clang. I think ideally we should make 2-stage build when 1-stage is temporary compiler build with gcc then 2-stage is full featured llvm build with compiler from stage 1.

**Comment by Erick555** [comment]
Size of extension build with gcc is 941.0 MB while current is 580.8 MB which illustrates why 2-stage build may be desirable here.

**Comment by jjardon** [comment]
@Erick555 @Lctrs would it be possible to land this soonish? This is blocking the update of GNOME to new freedesktop-sdk base: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1238

**Comment by abderrahim** [comment]
I've opened https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/pull/6 for the two-stage build

**Pull request merged**
