### PR TITLE
Update to 22.08 stable runtime

### PR DESCRIPTION
**Pull request by tim77**
Build takes a long time but it compiles successfully on my local machine with new runtime.

### CODE REVIEW

**Comment by Erick555** [comment]
Why do you need to build this? It's EOL for long time.

**Comment by tim77** [comment]
I was thinking about updating `io.github.kotatogram` and i am only at the beginning of my journey. :smile: `io.github.kotatogram` depends on:

```yml
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm12
```

What is proper way to replacing this in modern fd.o 22.08 or 23.08 runtime? Probably i should try to build `io.github.kotatogram` with LLVM which comes with fd.o runtime...

**Comment by Erick555** [comment]
The assumption is app will migrate to newer llvm alongside new runtime (similarly how gcc is updated in each runtime release). I don't know about this particular app but telegram [works](https://github.com/flathub/org.telegram.desktop/blob/beta/org.telegram.desktop.yml#L23) with latest llvm.

**Comment by tim77** [comment]
Understood, thanks! It turns out that updating `io.github.kotatogram` is not easy at this point without upstream which currently busy. I've opened issue in `io.github.kotatogram` and this PR make no sense, so closing it. I was in a hurry sorry for disturbing.

**Pull request closed without merging**
